### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by MrWelsch** [lzw-723/FXML-Viewer#2]
Hey, so I configured scenebuilder.home to /mnt/c/ProgramFiles/SceneBuilder/SceneBuilder.exe.
Whenever I try to open a fxml file the error message shown below pops up.

![grafik](https://user-images.githubusercontent.com/45096895/102538366-78319500-40ac-11eb-9211-eb6eff091014.png)

`java.io.FileNotFoundException: C:\home\kuma\Code\kochbuch\src\main\resources\Knuth\primary.fxml (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.readContentFromURL(FXOMDocument.java:389)
	at com.oracle.javafx.scenebuilder.app.DocumentWindowController.loadFromFile(DocumentWindowController.java:385)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFiles(SceneBuilderApp.java:665)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleOpenFilesAction(SceneBuilderApp.java:510)
	at com.oracle.javafx.scenebuilder.app.AppPlatform$MessageBoxDelegate.lambda$messageBoxDidGetMessage$0(AppPlatform.java:180)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by lzw-723** [comment]
I am sorry to reply you so late.
Look at the error message that the file does not exist. If you are a newly created fxml file, you should save it first, and then try to display it.
